"""Fresh initial setup

Revision ID: ce7f0b85a643
Revises: 
Create Date: 2026-06-20 19:06:13.110230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7f0b85a643'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=False),
    sa.Column('product', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('new_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('availability', sa.String(length=200), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_monitor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_monitor_scraped_at'), ['scraped_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_monitor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_monitor_scraped_at'))

    op.drop_table('price_monitor')
    # ### end Alembic commands ###
