"""add nullable url column

Revision ID: f5e8de8de83c
Revises: ce7f0b85a643
Create Date: 2026-06-21 08:43:06.964884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e8de8de83c'
down_revision = 'ce7f0b85a643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_monitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=800), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_monitor', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
